name: 🐛 Сообщение об ошибке [RU]
description: Сообщите о проблеме, которая должна быть устранена
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        **ИСПОЛЬЗУЙТЕ ЭТУ ФОРМУ ТОЛЬКО ДЛЯ БАГОВ**

        Voice-over-translation не гарантирует ни 100% работу с каждым видео, ни работу вообще. Если Voice-over-translation не переводит некоторые медиа, вероятнее всего, это не программная ошибка, и не стоит о ней сообщать здесь.
        Пожалуйста, сообщайте только об программных ошибках, таких как:
          * проблемы с меню
          * проблемы с функциями
          * другие ошибки/проблемы (не запрос функции)

        Убедитесь, что вы используете последнюю версию voice-over-translation.
        Возможно, ошибка, с которой вы столкнулись, уже исправлена.

        Пожалуйста, постарайтесь предоставить как можно больше информации.
  - type: checkboxes
    attributes:
      label: Есть ли issue, связанная с этой проблемой?
      description: Пожалуйста, [поищите здесь](https://github.com/ilyhalight/voice-over-translation/issues) чтобы узнать, существует ли уже issue, связанная с вашей проблемой.
      options:
        - label: Я изучил существующие issues.
          required: true
  - type: input
    id: script-version
    attributes:
      label: Какая версия voice-over-translation используется?
      description: Версию скрипта можно посмотреть в меню настроек кнопки перевода или менеджера пользовательских скриптов.
      placeholder: ex. 1.9.4
    validations:
      required: true
  - type: dropdown
    id: userscript-manager
    attributes:
      label: Выберите менеджер пользовательских скриптов, который вы используете
      description: Через менеджер пользовательских скриптов вы запускаете скрипт voice-over-translation
      options:
        - Tampermonkey
        - Violentmonkey
        - Greasemonkey
        - OrangeMonkey
        - AdGuard
        - FireMonkey
        - UserScripts
        - Other / Другой
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Выберите ваш браузер
      description: Браузер который вы используете
      options:
        - Chrome
        - Firefox
        - Edge
        - Opera
        - Safari
        - Other / Другой
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Введите вашу Операционную систему
      description: |
        Если не знаете точную версию, используйте одну из этих команд и скопируйте результат:

        Для MacOS и Linux: `uname -mprs`

        Для Windows: выполните в PowerShell:
        `"$([Environment]::OSVersion | ForEach-Object VersionString) $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" })"`
      placeholder: ex. Windows 10 20H2
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Какие шаги могут воспроизвести ошибку?
      description: Объясните ошибку и предоставьте шаги, которые могут ее воспроизвести.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Каково ожидаемое поведение?
      description: Если возможно, пожалуйста, предоставьте текст/скриншоты.
  - type: textarea
    id: what-you-see
    attributes:
      label: Что вы видите вместо этого?
      description: Если возможно, пожалуйста, предоставьте текст/скриншоты.
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: |
        Если у вас есть предположения об источнике бага, вы можете изложить их здесь.

        Если по вашему мнению это техническая ошибка, пожалуйста, предоставьте логи консоли.
